# .golangci.yml
version: "2"

run:
  timeout: 5m

linters:
  enable:
    # Essential linters for code correctness and style
    - errcheck # Checks for unchecked errors
    - govet # Reports suspicious constructs
    - staticcheck # A comprehensive suite of static analysis checks
    - unused # Checks for unused constants, functions, types, and variables
    - ineffassign # Detects ineffectual assignments

    # Additional useful linters
    - gosec # Security-focused linter
    - revive # A faster, more configurable linter than golint
    - misspell # Checks for misspelled words
    - bodyclose # Checks for unclosed HTTP response bodies
    - copyloopvar # Checks for loops that capture loop variables by reference
    - unconvert # Reports unnecessary type conversions
