version: '3.8'

services:
  gochat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gochat-server
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=:8080
      - ALLOWED_ORIGINS=http://localhost:8080,http://localhost:3000
      - MAX_MESSAGE_SIZE=512
      - RATE_LIMIT_BURST=5
      - RATE_LIMIT_REFILL_INTERVAL=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    # Uncomment to use .env file for configuration
    # env_file:
    #   - .env
    networks:
      - gochat-network

networks:
  gochat-network:
    driver: bridge
